name: 自动发布 Release
on:
  push:
    branches:
      - main  # 监听主分支的代码变动
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 允许创建 release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # 获取所有历史记录，确保能获取到所有标签
          
      - name: Get the latest tag
        id: get_latest_tag
        run: |
          # 获取最新标签
          latest_tag=$(git tag --list 'v*' | sort -V | tail -n 1)
          echo "Latest tag: $latest_tag"
          if [ -z "$latest_tag" ]; then
            echo "No tags found, setting initial tag to v2.1"
            new_tag="v2.1"
          else
            # 提取版本号，不包含'v'前缀
            version=${latest_tag#v}
            # 分割主版本号和次版本号
            major=$(echo $version | cut -d '.' -f1)
            minor=$(echo $version | cut -d '.' -f2)
            
            # 如果次版本号是9，则主版本号加1，次版本号重置为0
            if [ "$minor" = "9" ]; then
              major=$((major + 1))
              minor=0
            else
              # 否则只递增次版本号
              minor=$((minor + 1))
            fi
            
            # 组合新的标签
            new_tag="v${major}.${minor}"
          fi
          
          # 检查新标签是否已存在
          if git rev-parse "$new_tag" >/dev/null 2>&1; then
            echo "Tag $new_tag already exists, skipping release"
            echo "SKIP_RELEASE=true" >> $GITHUB_ENV
          else
            echo "SKIP_RELEASE=false" >> $GITHUB_ENV
            echo "NEW_TAG=$new_tag" >> $GITHUB_ENV
          fi

      - name: Create and Push Tag
        if: env.SKIP_RELEASE != 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}

      - name: Create GitHub release
        if: env.SKIP_RELEASE != 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEW_TAG }}
          release_name: ${{ env.NEW_TAG }}
          draft: false
          prerelease: false
          body: |
            ## Changes
            - See the [commit history](https://github.com/${{ github.repository }}/commits/${{ env.NEW_TAG }}) for more details.
